spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/numbers
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
        ddl-auto: update
